### ISSUE TITLE
Bidirectional slash in templates

### ISSUE THREAD

**Issue by kmineshima** [mynlp/ccg2lambda#11]
Often we may want to use bidirectional slash, `A|B`, which means both `A\B` and `A/B`, as syntactic sugar in templates, for, usually, the direction of slash does not matter when writing templates. E.g., the entries for `(S\NP)/NP` and `(S\NP)\NP` etc can be replaced by the single entry for `(S|NP)|NP`, which is more general and applicable to both English and Japanese.

**Comment by pasmargo** [comment]
Thank you for the feature suggestion! I will try to implement it this week.

**Comment by pasmargo** [comment]
@kmineshima Did you have time to check if the implementation in `vertical` branch works as you expected?

**Comment by kmineshima** [comment]
@pasmargo I think it is ready to merge this branch to master. Now the templates (`en/semantic_templates_en_event.yaml`) are changed to a vertical version, which works better. For Japanese, the templates are the same as before.

**Comment by pasmargo** [comment]
Thank you for checking the branch!
I have merged it.
