### ISSUE TITLE
outdated MathJax CDN links in scripts/visualization_tools.py

### ISSUE THREAD

**Issue by DrXyzzy** [mynlp/ccg2lambda#20]
Two links to MathJax in `scripts/visualization_tools.py`
```
src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
```
should probably be updated. See [MathJax CDN shutting down on April 30, 2017. ](https://www.mathjax.org/cdn-shutting-down/). You could replace with e.g. 
```
src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
```

This affects display of e.g., graphdebug.html during install steps in Google Chrome. There's an example at this [walkthrough of ccg2lambda install](https://cocalc.com/share/cd3c25e4-5fbd-439b-9604-6011584af918/CCG2/ccg2lambdatest.sagews?viewer=share) in CoCalc.

**Comment by pasmargo** [comment]
I was not aware of MathJax CDN shutting down. Thank you very much for the update!
I have changed the links following your suggestion. However, I don't have Google Chrome at hand to test it.
Please let us know if the problem has been fixed (it works correctly for Firefox and Chromium).
Thank you again!

By the way: the CoCalc walkthrough is quite cool. I have learned quite a few things. Thanks!

**Comment by DrXyzzy** [comment]
I tested the new code in Google Chrome and Chrome now displays the diagram without patching graphdebug.html. Thank you!

**Comment by pasmargo** [comment]
Thank you very much for testing it on Google Chrome. That is very much appreciated!
I will close the issue then.
Thanks a lot!
