### ISSUE TITLE
ccg_treee and ccg_xml

### ISSUE THREAD

**Issue by khadekirti** [mynlp/ccg2lambda#4]
Although there are multiple function using ccg_tree and ccg_xml, i did not see any function returning any of them. Can you please guide me?

**Comment by pasmargo** [comment]
The function `build_ccg_tree` in `scripts/ccg2lambda_tools.py` returns a `ccg_tree`, which is a tree data structure. It receives a `ccg_xml` as an argument.

In ccg2lambda, we mainly work with `ccg_tree`, because it is a bit easier to traverse.

**Comment by khadekirti** [comment]
where is ccg_xml coming from?

**Comment by pasmargo** [comment]
In `scripts/semparse.py` we load the *sem.xml file as:

```
parser = etree.XMLParser(remove_blank_text=True)
root = etree.parse(args.ccg, parser)
```

And then we iterate over the "sentence" spans:

```
for sentence in root.findall('.//sentence')
    [...]
```

The `sentence` is what we call `ccg_xml` as the first argument of `assign_semantics_to_ccg`.
