### ISSUE TITLE
Import visualization of n-best parses

### ISSUE THREAD

**Issue by kmineshima** [mynlp/ccg2lambda#8]
To import the functionality to visualize n-best parses from ccg2mathml.py at the old repo.

The old script takes three arguments and output n-best derivation trees.
```
python ccg2mathml.py <ccg_trees.xml> <categories_template.txt> <nbest>
```

**Comment by pasmargo** [comment]
I have implemented this feature. Now, most of the scripts accept a `--nbest <int>` flag with which you can specify how many n-best trees you want to parse or visualize.
